/**
 * Type definitions for RBMK Reactor Simulation
 *
 * This file defines the core types for simulating a simplified RBMK reactor
 * with uranium fuel atoms, control rods, and neutron particles.
 *
 * Based on real RBMK-1000 specifications (Chernobyl Unit 4 type).
 */

/**
 * Position in 2D space
 */
export interface Position {
  x: number;
  y: number;
}

/**
 * Velocity vector in 2D space
 */
export interface Velocity {
  vx: number;
  vy: number;
}

/**
 * Uranium fuel channel in the reactor core
 *
 * RBMK-1000 has 1,693 fuel channels arranged in a square lattice.
 * Each channel contains enriched uranium dioxide (UO2) fuel.
 */
export interface Atom {
  id: string;
  position: Position;
  /** Grid coordinates for layout */
  gridX: number;
  gridY: number;
  /** Current energy level / reaction intensity (0-1) */
  energy: number;
  /** Time since last neutron emission (ms) */
  timeSinceEmission: number;
  /** Visual radius in pixels */
  radius: number;
  /** Neutrons emitted from this atom */
  emittedCount: number;
}

/**
 * Control rod that absorbs neutrons
 *
 * RBMK reactors use boron carbide (B4C) control rods.
 * Real RBMK-1000 specs:
 * - 211 control rods total (manual + emergency protection)
 * - Insertion time: 18-21 seconds (critically slow!)
 * - B-10 absorption cross-section: 3,840 barns
 * - Active zone height: 7 meters
 */
export interface ControlRod {
  id: string;
  /** X position (fixed) */
  x: number;
  /** Y position (variable - controlled by slider, 0 = top/raised, height = bottom/lowered) */
  y: number;
  /** Width of the rod */
  width: number;
  /** Height of the rod when fully inserted */
  maxHeight: number;
  /** Current insertion depth (0-1, where 0 = fully raised, 1 = fully lowered) */
  insertion: number;
  /** Number of neutrons absorbed (for statistics) */
  absorbedCount: number;
  /** Visual state for absorption animation */
  isAbsorbing: boolean;
  lastAbsorptionTime: number;
  /** Target insertion (for smooth animation to user-set value) */
  targetInsertion: number;
}

/**
 * Free neutron particle
 *
 * Real physics:
 * - Thermal neutrons: ~2200 m/s velocity
 * - Fast neutrons: ~20,000 km/s velocity (pre-moderation)
 * - Average lifetime in reactor: ~0.1 seconds
 * - U-235 fission releases 2.43 neutrons on average
 */
export interface Neutron {
  id: string;
  position: Position;
  velocity: Velocity;
  /** Age of the neutron in milliseconds */
  age: number;
  /** Speed in pixels per frame */
  speed: number;
  /** Visual radius */
  radius: number;
  /** Whether neutron was just created (for trail effects) */
  isNew: boolean;
  /** Previous positions for trail rendering */
  trail: Position[];
  /** Number of times neutron has bounced off containment walls (for absorption) */
  wallBounces: number;
}

/**
 * Heat grid for temperature visualization
 *
 * Represents a 2D grid of temperature values for visualizing reactor heat.
 * Heat is generated by fission reactions and diffuses to surrounding areas.
 */
export interface HeatGrid {
  /** Width of grid in cells */
  width: number;
  /** Height of grid in cells */
  height: number;
  /** Cell size in pixels */
  cellSize: number;
  /** 2D array of temperature values (0-1, where 0 = cold, 1 = max heat) */
  temperatures: number[][];
}

/**
 * Simulation state
 */
export interface SimulationState {
  atoms: Atom[];
  controlRods: ControlRod[];
  neutrons: Neutron[];
  /** Heat grid for temperature visualization */
  heatGrid: HeatGrid;
  /** Whether simulation is running */
  isRunning: boolean;
  /** Simulation speed multiplier */
  speed: number;
  /** Total neutrons emitted */
  totalEmitted: number;
  /** Total neutrons absorbed by rods */
  totalAbsorbed: number;
  /** Total neutrons absorbed by atoms (fission events) */
  totalFissions: number;
  /** Current reaction rate (neutrons per second) */
  reactionRate: number;
  /** Average reactor temperature (0-1) */
  reactorTemp: number;
  /** Timestamp of last frame */
  lastFrameTime: number;
  /** Animation frame ID (for RAF cancellation) */
  animationFrameId: number | null;
}

/**
 * Configuration for reactor simulation
 *
 * Based on real RBMK-1000 reactor physics, scaled for visualization.
 *
 * Real RBMK-1000 properties:
 * - 1,693 pressure tubes (fuel channels) in 11.8m x 11.8m core
 * - 211 control rods (manual control + emergency protection system)
 * - Core active zone: 7m high
 * - Thermal neutron velocity: ~2200 m/s
 * - Control rod insertion time: 18-21 seconds (slow!)
 * - Boron-10 absorption cross-section: 3,840 barns
 * - U-235 fission cross-section: 580 barns (thermal neutrons)
 * - Average neutrons per U-235 fission: 2.43
 */
export interface ReactorConfig {
  /** Reactor grid dimensions (scaled down from 1,693 channels) */
  grid: {
    /** Number of fuel channels horizontally */
    columns: number;
    /** Number of fuel channels vertically */
    rows: number;
    /** Spacing between fuel channels (pixels) */
    spacing: number;
  };

  /** Fuel channel properties (U-235 enriched fuel) */
  atom: {
    /** Visual radius (pixels) */
    radius: number;
    /** Base emission rate (neutrons per second per atom) */
    baseEmissionRate: number;
    /** Energy decay rate per frame (cooling) */
    energyDecay: number;
    /** Energy gain when struck by neutron (chain reaction) */
    energyGain: number;
    /** Minimum energy to emit neutron */
    emissionThreshold: number;
    /** Neutrons released per fission event (real: 2.43) */
    neutronsPerFission: number;
  };

  /** Control rod properties (Boron-10 Carbide) */
  controlRod: {
    /** Width of rod (pixels) */
    width: number;
    /** Number of control rods (real: 211, scaled down for viz) */
    count: number;
    /** Neutron absorption probability (based on 3,840 barn cross-section) */
    absorptionProbability: number;
    /** Animation duration for absorption effect (ms) */
    absorptionEffectDuration: number;
    /** Insertion/withdrawal speed (real: 18-21 seconds for full insertion) */
    insertionSpeed: number; // units per second (0-1 range over this time)
  };

  /** Neutron properties */
  neutron: {
    /** Visual radius (pixels) */
    radius: number;
    /** Base speed (pixels per frame at 60fps, scaled from 2200 m/s) */
    baseSpeed: number;
    /** Speed variation (+/- this fraction) */
    speedVariation: number;
    /** Maximum age before decay (ms, real: ~100ms) */
    maxAge: number;
    /** Maximum number of neutrons in simulation (performance limit) */
    maxCount: number;
    /** Probability of causing fission vs being absorbed (related to 580 barn cross-section) */
    fissionProbability: number;
    /** Trail length for visual effect */
    trailLength: number;
  };

  /** Physics constants */
  physics: {
    /** Collision detection threshold (pixels) */
    collisionThreshold: number;
    /** Boundary bounce damping (0-1) */
    boundaryDamping: number;
    /** Enable collision with other neutrons */
    neutronCollisions: boolean;
  };

  /** Simulation parameters */
  simulation: {
    /** Default speed multiplier */
    defaultSpeed: number;
    /** Target frames per second */
    targetFPS: number;
    /** Enable requestAnimationFrame (vs setInterval) */
    useRAF: boolean;
  };
}

/**
 * Collision detection result
 */
export interface CollisionResult {
  /** Type of collision */
  type: "atom" | "rod" | "boundary" | "neutron" | "none";
  /** Object ID that was hit (if applicable) */
  objectId?: string;
  /** New velocity after collision (if applicable) */
  newVelocity?: Velocity;
}
