name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build App
        run: yarn build:app

      - name: Build Storybook
        run: yarn build:storybook

      - name: Combine builds for GitHub Pages
        run: |
          mkdir -p gh-pages
          cp -r dist/app/* gh-pages/

          # Rename app's index.html to demo.html
          mv gh-pages/index.html gh-pages/demo.html

          cp -r dist/storybook gh-pages/storybook

          # Create index redirect page at root
          cat > gh-pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Catalyst UI</title>
            <style>
              * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }

              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
              }

              .container {
                text-align: center;
                max-width: 600px;
                padding: 2rem;
              }

              h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                background: linear-gradient(90deg, #00D4FF, #FF00E5);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
              }

              p {
                font-size: 1.2rem;
                margin-bottom: 2rem;
                opacity: 0.9;
              }

              .buttons {
                display: flex;
                gap: 1rem;
                justify-content: center;
                flex-wrap: wrap;
              }

              a {
                display: inline-block;
                padding: 1rem 2rem;
                background: rgba(255, 255, 255, 0.1);
                border: 2px solid rgba(255, 255, 255, 0.3);
                border-radius: 8px;
                color: white;
                text-decoration: none;
                font-weight: 600;
                transition: all 0.3s ease;
                backdrop-filter: blur(10px);
              }

              a:hover {
                background: rgba(255, 255, 255, 0.2);
                border-color: rgba(255, 255, 255, 0.5);
                transform: translateY(-2px);
              }

              .storybook {
                background: rgba(255, 100, 229, 0.2);
                border-color: rgba(255, 100, 229, 0.4);
              }

              .storybook:hover {
                background: rgba(255, 100, 229, 0.3);
                border-color: rgba(255, 100, 229, 0.6);
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Catalyst UI</h1>
              <p>A React component library built with Vite, TypeScript, and Tailwind CSS</p>
              <div class="buttons">
                <a href="./demo.html">View Demo App</a>
                <a href="./storybook/" class="storybook">Browse Components</a>
              </div>
            </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
